ISS_space_station/ISS_space_station/Models/IIS/SpaceStationDetails.cs
namespace ISS_space_station.Models.IIS
{
    public class SpaceStationDetails
    {
        public string Name { get; set; }
        public int Id { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public double Altitude { get; set; }
        public double Velocity { get; set; }
        public string Visibility { get; set; }
        public double Footprint { get; set; }
        public double Timestamp { get; set; }
        public double Daynum { get; set; }
        public double SolarLat { get; set; }
        public double SolarLong { get; set; }
        public string Units { get; set; }

    }
}

ISS_space_station/ISS_space_station/Controllers/HomeController.cs
using ISS_space_station.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ISS_space_station.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

ISS_space_station/ISS_space_station/Controllers/SpaceController.cs
using ISS_space_station.Interfaces;
using ISS_space_station.Models.IIS;
using Microsoft.AspNetCore.Mvc;

namespace ISS_space_station.Controllers
{
    public class SpaceController : Controller
    {
        private IDownload _download;

        public SpaceController(IDownload download)
        {
            _download = download;
        }

        public async Task<IActionResult> Index()
        {
            var info = await _download.GetData();

            if (info == null)
            {
                return NotFound();
            }

            return View(info); 
        }
    }
}

ISS_space_station/ISS_space_station/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ISS_space_station/ISS_space_station/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ISS_space_station</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ISS_space_station.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ISS_space_station</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Space" asp-action="Index">Stacja Kosmiczna</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ISS_space_station - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ISS_space_station/ISS_space_station/Views/Space/Index.cshtml
@model ISS_space_station.Models.IIS.SpaceStationDetails
@{
    ViewData["Title"] = "IIS position";
}
<form>
    <label for="statusField">Długość i szerokość geograficzna:</label>
    <input type="text" id="statusField" value="@((Model.Latitude).ToString().Replace(',','.'))" readonly />
    <input type="text" id="statusField" value="@((Model.Longitude).ToString().Replace(',','.'))" readonly />
    <label for="statusField">Szybkość</label>
    <input type="text" id="statusField" value="@((Model.Velocity).ToString().Replace(',','.')) km" readonly />
</form>
<div id="map" style="width: 100%; height: 800px;">
    <script>
        var map = L.map('map').setView([@((Model.Latitude).ToString().Replace(',', '.')), @((Model.Longitude).ToString().Replace(',', '.'))], 4);

        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map)

        // Dodaje marker/pineskę na szerokosc i dlugosc geo
        var marker = L.marker([@((Model.Latitude).ToString().Replace(',', '.')), @((Model.Longitude).ToString().Replace(',', '.'))]).addTo(map);

        // Dodaje podpis do pineski
        marker.bindPopup("<b>Aktualne położenie ISS</b>").openPopup();
    </script>
</div>